name: Rush
main: fr.cartooncraft.rush.RushPlugin
version: 1.0.0
commands:
    rush:
        description: Rush command.
        usage: /rush
    stats:
        description: Get stats for a player (Rush)
        usage: /stats <player>